<?php
/**
 * QuizSphere - Student dashboard
 * Authenticated. Shows real user info (name, xp, level, streak) and recent
 * quizzes. Chart remains a placeholder (analytics arrive in a later phase).
 */
require_once __DIR__ . '/../includes/bootstrap.php';

try {
    $client = SupabaseClient::fromConfig();
    $auth = new Auth($client);
    $repo = new QuizRepository($client);
} catch (SupabaseException $e) {
    $auth = null;
}

if (!$auth || !$auth->check()) {
    set_flash('error', 'Please log in to view your dashboard.');
    redirect('/login.php');
}

$user = $auth->user();
$profile = $auth->profile() ?: [
    'full_name' => $user['full_name'] ?? 'Learner',
    'email'     => $user['email'] ?? '',
    'xp'        => 0,
    'level'     => 1,
    'streak'    => 0,
];

$token = $auth->accessToken();
$recent = [];
$quizCount = 0;
if ($token) {
    try {
        $recent = $repo->listUserQuizzes($auth->id(), $token, 5);
        $quizCount = count($recent);
    } catch (SupabaseException $e) {
        $recent = [];
    }
}

$name = trim($profile['full_name'] !== '' ? $profile['full_name'] : ($user['full_name'] ?? 'Learner'));
$first = mb_substr(trim($name), 0, 1) ?: 'L';
$xp = (int) ($profile['xp'] ?? 0);
$level = (int) ($profile['level'] ?? 1);
$streak = (int) ($profile['streak'] ?? 0);

$page_title = 'Dashboard';
$active_page = 'pages';
require __DIR__ . '/../includes/head.php';
?>
<body>
<div class="dashboard-shell">

  <?php $dashboard_active = 'dashboard'; require __DIR__ . '/../includes/sidebar.php'; ?>

  <main class="dashboard-main" id="dashboard-analytics">
    <!-- Top bar -->
    <div class="topbar">
      <div>
        <h1 class="h4 mb-1">Welcome back, <?php echo e($name); ?></h1>
        <p class="text-muted-ink mb-0">Here's your learning overview.</p>
      </div>
      <div class="d-flex align-items-center gap-3">
        <a href="<?php echo url('/pages/generate.php'); ?>" class="btn btn-brand d-none d-sm-inline-flex"><i class="bi bi-plus-lg me-2"></i>New Quiz</a>
        <span class="avatar-circle"><?php echo e($first); ?></span>
      </div>
    </div>

    <!-- Quick actions -->
    <div class="d-flex flex-wrap gap-2 mb-4">
      <a href="<?php echo url('/pages/generate.php'); ?>" class="btn btn-brand"><i class="bi bi-robot me-2"></i>Generate Quiz</a>
      <a href="<?php echo url('/pages/upload.php'); ?>" class="btn btn-outline-brand"><i class="bi bi-file-earmark-pdf me-2"></i>Upload PDF</a>
      <a href="<?php echo url('/pages/leaderboard.php'); ?>" class="btn btn-outline-brand"><i class="bi bi-trophy me-2"></i>Leaderboard</a>
      <a href="<?php echo url('/pages/certificates.php'); ?>" class="btn btn-outline-brand"><i class="bi bi-award me-2"></i>Certificates</a>
    </div>

    <!-- Stat tiles -->
    <div class="row g-3 mb-4">
      <div class="col-6 col-lg-3">
        <div class="stat-tile">
          <div class="stat-label mb-1">Total Quizzes</div>
          <div class="stat-value"><?php echo (int) $quizCount; ?></div>
          <div class="small text-muted-ink">Generated by you</div>
        </div>
      </div>
      <div class="col-6 col-lg-3">
        <div class="stat-tile">
          <div class="stat-label mb-1">Average Score</div>
          <div class="stat-value" id="stat-avg-score">—</div>
          <div class="small text-muted-ink" data-avg-sub>After your first attempt</div>
        </div>
      </div>
      <div class="col-6 col-lg-3">
        <div class="stat-tile">
          <div class="stat-label mb-1">Learning Streak</div>
          <div class="stat-value"><?php echo (int) $streak; ?> <span class="fs-6 text-muted-ink">days</span></div>
          <div class="small text-muted-ink"><i class="bi bi-fire text-warning"></i> Keep it going!</div>
        </div>
      </div>
      <div class="col-6 col-lg-3">
        <div class="stat-tile">
          <div class="d-flex justify-content-between align-items-center mb-1">
            <span class="stat-label">XP / Level</span>
            <span class="badge-soft" id="leaderboard-rank-hint"></span>
          </div>
          <div class="stat-value"><?php echo number_format($xp); ?> <span class="fs-6 text-muted-ink">XP</span></div>
          <div class="mt-2" id="level-progress-wrap">
            <div class="progress" style="height: 6px;">
              <div class="progress-bar" id="level-progress" style="width:0%"></div>
            </div>
            <div class="small text-muted-ink mt-1" id="level-progress-label">Level <?php echo (int) $level; ?></div>
          </div>
        </div>
      </div>
    </div>

    <div class="row g-4">
      <!-- Left column -->
      <div class="col-lg-8">
        <!-- Performance chart -->
        <div class="card p-4 mb-4">
          <div class="d-flex justify-content-between align-items-center mb-3">
            <h5 class="mb-0">Performance Overview</h5>
            <span class="badge-soft">Across attempts</span>
          </div>
          <div style="height: 260px;">
            <canvas id="performance-chart"></canvas>
          </div>
        </div>

        <!-- Recent quizzes -->
        <div class="card p-4">
          <div class="d-flex justify-content-between align-items-center mb-3">
            <h5 class="mb-0">Recent Quizzes</h5>
            <a href="<?php echo url('/pages/my_quizzes.php'); ?>" class="small">View all</a>
          </div>
          <div class="table-responsive">
            <table class="table align-middle">
              <thead>
                <tr class="text-muted-ink small">
                  <th>Quiz</th>
                  <th>Topic</th>
                  <th>Score</th>
                  <th>Date</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <?php if ($recent): ?>
                  <?php foreach ($recent as $q): ?>
                  <tr>
                    <td class="fw-semibold"><?php echo e($q['title'] ?? 'Quiz'); ?></td>
                    <td><?php echo e($q['topic'] ?? '—'); ?></td>
                    <td><span class="badge-soft"><?php echo e(ucfirst($q['difficulty'] ?? 'medium')); ?></span></td>
                    <td class="text-muted-ink"><?php echo e(date('M j', strtotime((string) ($q['created_at'] ?? 'now')))); ?></td>
                    <td><a href="<?php echo url('/pages/quiz.php?id=' . urlencode($q['id'])); ?>" class="small">Take</a></td>
                  </tr>
                  <?php endforeach; ?>
                <?php else: ?>
                  <tr>
                    <td colspan="5" class="text-center text-muted-ink py-4">
                      No quizzes yet. <a href="<?php echo url('/pages/generate.php'); ?>">Generate your first quiz</a>.
                    </td>
                  </tr>
                <?php endif; ?>
              </tbody>
            </table>
          </div>
        </div>
      </div>

      <!-- Right column -->
      <div class="col-lg-4">
        <!-- Recommended practice -->
        <div class="card p-4 mb-4">
          <h5 class="mb-3">Recommended Practice</h5>
          <div id="recommendation-list">
            <p class="text-muted-ink small mb-0"><i class="bi bi-hourglass-split me-1"></i>Checking your progress...</p>
          </div>
          <div class="form-alert mt-3" hidden id="practice-alert"></div>
        </div>

        <!-- Weak / developing / strong areas -->
        <div class="card p-4 mb-4">
          <h5 class="mb-3">Concept Mastery</h5>
          <div class="mb-4">
            <div class="small fw-semibold text-danger mb-2"><i class="bi bi-x-circle me-1"></i>Weak Areas</div>
            <div id="weak-list"><p class="text-muted-ink small mb-0">No data yet.</p></div>
          </div>
          <div class="mb-4">
            <div class="small fw-semibold text-warning mb-2"><i class="bi bi-arrow-up-circle me-1"></i>Developing</div>
            <div id="developing-list"><p class="text-muted-ink small mb-0">No data yet.</p></div>
          </div>
          <div>
            <div class="small fw-semibold text-success mb-2"><i class="bi bi-check-circle me-1"></i>Strong Areas</div>
            <div id="strong-list"><p class="text-muted-ink small mb-0">No data yet.</p></div>
          </div>
        </div>

        <!-- Insights -->
        <div class="card p-4">
          <h5 class="mb-3"><i class="bi bi-lightbulb me-2"></i>Learning Insights</h5>
          <ul class="ps-0 list-unstyled d-flex flex-column gap-2 mb-0" id="insights-list">
            <li class="text-muted-ink small"><i class="bi bi-hourglass-split me-1"></i>Checking your progress...</li>
          </ul>
        </div>

        <!-- Achievements (JS-loaded) -->
        <div class="card p-4 mt-4">
          <div class="d-flex justify-content-between align-items-center mb-3">
            <h5 class="mb-0"><i class="bi bi-trophy me-2"></i>Achievements</h5>
            <span class="badge-soft" id="achievement-count"></span>
          </div>
          <div id="achievements-grid" class="row g-2"></div>
        </div>

        <!-- Certificates (JS-loaded) -->
        <div class="card p-4 mt-4">
          <div class="d-flex justify-content-between align-items-center mb-3">
            <h5 class="mb-0"><i class="bi bi-award me-2"></i>Certificates</h5>
            <a href="<?php echo url('/pages/certificates.php'); ?>" class="small">View all</a>
          </div>
          <div id="certificates-preview">
            <p class="text-muted-ink small mb-0"><i class="bi bi-hourglass-split me-1"></i>Checking...</p>
          </div>
        </div>
      </div>
    </div>
  </main>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.1/dist/chart.umd.min.js"></script>
<script src="<?php echo url('/assets/js/app.js'); ?>"></script>
</body>
</html>
