<?php
/**
 * QuizSphere - Student dashboard
 * Authenticated. Shows real user info (name, xp, level, streak) and recent
 * quizzes. Chart and analytics load via real Supabase/FastAPI analytics.
 */
require_once __DIR__ . '/../includes/bootstrap.php';

try {
    $client = SupabaseClient::fromConfig();
    $auth = new Auth($client);
    $repo = new QuizRepository($client);
} catch (SupabaseException $e) {
    $auth = null;
}

if (!$auth || !$auth->check()) {
    set_flash('error', 'Please log in to view your dashboard.');
    redirect('/login.php');
}

$user = $auth->user();
$profile = $auth->profile() ?: [
    'full_name' => $user['full_name'] ?? 'Learner',
    'email'     => $user['email'] ?? '',
    'xp'        => 0,
    'level'     => 1,
    'streak'    => 0,
];

$token = $auth->accessToken();
$recent = [];
$quizCount = 0;
if ($token) {
    try {
        $recent = $repo->listUserQuizzes($auth->id(), $token, 5);
        $quizCount = count($recent);
    } catch (SupabaseException $e) {
        $recent = [];
    }
}

$name = trim($profile['full_name'] !== '' ? $profile['full_name'] : ($user['full_name'] ?? 'Learner'));
$first = mb_substr(trim($name), 0, 1) ?: 'L';
$xp = (int) ($profile['xp'] ?? 0);
$level = (int) ($profile['level'] ?? 1);
$streak = (int) ($profile['streak'] ?? 0);

$page_title = 'Dashboard';
$active_page = 'pages';
require __DIR__ . '/../includes/head.php';
?>
<body>
<div class="dashboard-shell">

  <?php $dashboard_active = 'dashboard'; require __DIR__ . '/../includes/sidebar.php'; ?>

  <main class="dashboard-main" id="dashboard-analytics">
    <!-- Top bar -->
    <div class="topbar">
      <div>
        <h1 class="h4 mb-1 fw-bold text-ink-900">Dashboard</h1>
        <p class="text-muted-ink mb-0 small">Overview of your learning progress &amp; quiz activity.</p>
      </div>
      <div class="d-flex align-items-center gap-3">
        <a href="<?php echo url('/pages/generate.php'); ?>" class="btn btn-brand btn-sm d-none d-sm-inline-flex">
          <i class="bi bi-plus-lg me-1"></i>New Quiz
        </a>
        <div class="topbar-user-pill d-flex align-items-center gap-2">
          <span class="avatar-circle avatar-circle-sm"><?php echo e($first); ?></span>
          <div class="d-none d-md-block text-start" style="line-height: 1.2;">
            <div class="fw-semibold text-ink-900 small"><?php echo e($name); ?></div>
            <div class="text-muted-ink" style="font-size: 0.72rem;">Level <?php echo (int) $level; ?></div>
          </div>
        </div>
      </div>
    </div>

    <!-- Welcome Hero Banner -->
    <div class="dashboard-welcome-hero mb-4">
      <div class="d-flex flex-column flex-md-row justify-content-between align-items-start align-items-md-center gap-3">
        <div>
          <div class="d-inline-flex align-items-center gap-2 badge-soft text-brand mb-2">
            <i class="bi bi-sparkles"></i> AI Learning Platform
          </div>
          <h2 class="h4 fw-bold mb-1 text-ink-900">Welcome back, <?php echo e($name); ?>!</h2>
          <p class="text-muted-ink mb-0">
            You're on a <strong class="text-ink-900"><i class="bi bi-fire text-warning me-1"></i><?php echo (int) $streak; ?>-day streak</strong>. Ready to test your knowledge or generate a new challenge?
          </p>
        </div>
        <div class="d-flex flex-wrap gap-2 flex-shrink-0">
          <a href="<?php echo url('/pages/generate.php'); ?>" class="btn btn-brand">
            <i class="bi bi-robot me-1"></i>Generate Quiz
          </a>
          <a href="<?php echo url('/pages/upload.php'); ?>" class="btn btn-outline-brand">
            <i class="bi bi-file-earmark-pdf me-1"></i>Upload PDF
          </a>
          <a href="<?php echo url('/pages/coach.php'); ?>" class="btn btn-outline-brand">
            <i class="bi bi-chat-dots me-1"></i>AI Coach
          </a>
        </div>
      </div>
    </div>

    <!-- Stat tiles (Row) -->
    <div class="row g-3 mb-4">
      <!-- Tile 1: Total Quizzes -->
      <div class="col-12 col-sm-6 col-xl-3">
        <div class="stat-tile">
          <div class="d-flex align-items-start justify-content-between">
            <div>
              <div class="stat-label mb-1">Total Quizzes</div>
              <div class="stat-value"><?php echo (int) $quizCount; ?></div>
              <div class="small text-muted-ink mt-1">Generated by you</div>
            </div>
            <div class="stat-icon-wrap stat-icon-indigo">
              <i class="bi bi-journal-check"></i>
            </div>
          </div>
        </div>
      </div>

      <!-- Tile 2: Average Score -->
      <div class="col-12 col-sm-6 col-xl-3">
        <div class="stat-tile">
          <div class="d-flex align-items-start justify-content-between">
            <div>
              <div class="stat-label mb-1">Average Score</div>
              <div class="stat-value" id="stat-avg-score">—</div>
              <div class="small text-muted-ink mt-1" data-avg-sub>After your first attempt</div>
            </div>
            <div class="stat-icon-wrap stat-icon-emerald">
              <i class="bi bi-graph-up-arrow"></i>
            </div>
          </div>
        </div>
      </div>

      <!-- Tile 3: Learning Streak -->
      <div class="col-12 col-sm-6 col-xl-3">
        <div class="stat-tile">
          <div class="d-flex align-items-start justify-content-between">
            <div>
              <div class="stat-label mb-1">Learning Streak</div>
              <div class="stat-value"><?php echo (int) $streak; ?> <span class="fs-6 text-muted-ink fw-normal">days</span></div>
              <div class="small text-muted-ink mt-1"><i class="bi bi-fire text-warning me-1"></i>Keep it going!</div>
            </div>
            <div class="stat-icon-wrap stat-icon-amber">
              <i class="bi bi-fire"></i>
            </div>
          </div>
        </div>
      </div>

      <!-- Tile 4: XP & Level -->
      <div class="col-12 col-sm-6 col-xl-3">
        <div class="stat-tile">
          <div class="d-flex align-items-start justify-content-between mb-1">
            <div>
              <div class="stat-label mb-1">XP &amp; Level</div>
              <div class="stat-value"><?php echo number_format($xp); ?> <span class="fs-6 text-muted-ink fw-normal">XP</span></div>
            </div>
            <div class="stat-icon-wrap stat-icon-violet">
              <i class="bi bi-star-fill"></i>
            </div>
          </div>
          <div class="mt-2" id="level-progress-wrap">
            <div class="d-flex justify-content-between align-items-center mb-1">
              <div class="small text-muted-ink" id="level-progress-label">Level <?php echo (int) $level; ?></div>
              <span class="badge-soft" id="leaderboard-rank-hint"></span>
            </div>
            <div class="progress" style="height: 6px;">
              <div class="progress-bar" id="level-progress" style="width:0%"></div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Row 1: Quiz Activity (Bar Chart) + Insights -->
    <div class="row g-4 mb-4">
      <div class="col-lg-8">
        <div class="card p-4 h-100">
          <div class="d-flex justify-content-between align-items-center mb-3">
            <div>
              <h5 class="mb-1 fw-bold text-ink-900"><i class="bi bi-bar-chart-line text-brand me-2"></i>Quiz Activity</h5>
              <p class="text-muted-ink small mb-0">Your scores over time</p>
            </div>
            <span class="badge-soft">Recent Attempts</span>
          </div>
          <div style="height: 280px; position: relative;">
            <canvas id="quiz-activity-chart"></canvas>
          </div>
        </div>
      </div>

      <div class="col-lg-4 d-flex flex-column gap-3">
        <!-- Recommended Practice -->
        <div class="card p-4 flex-grow-1">
          <div class="d-flex justify-content-between align-items-center mb-3">
            <h5 class="mb-0 fw-bold text-ink-900"><i class="bi bi-bullseye text-brand me-2"></i>Next Steps</h5>
          </div>
          <div id="recommendation-list">
            <p class="text-muted-ink small mb-0"><i class="bi bi-hourglass-split me-1"></i>Checking your progress...</p>
          </div>
          <div class="form-alert mt-3" hidden id="practice-alert"></div>
        </div>

        <!-- Insights -->
        <div class="card p-4 flex-grow-1">
          <h5 class="mb-3 fw-bold text-ink-900"><i class="bi bi-lightbulb text-warning me-2"></i>Insights</h5>
          <ul class="ps-0 list-unstyled d-flex flex-column gap-2 mb-0" id="insights-list">
            <li class="text-muted-ink small"><i class="bi bi-hourglass-split me-1"></i>Checking...</li>
          </ul>
        </div>
      </div>
    </div>

    <!-- Row 2: Topic Performance (Horizontal Bar) + Score Distribution (Doughnut) -->
    <div class="row g-4 mb-4">
      <div class="col-lg-7">
        <div class="card p-4 h-100">
          <div class="d-flex justify-content-between align-items-center mb-3">
            <div>
              <h5 class="mb-1 fw-bold text-ink-900"><i class="bi bi-layout-text-sidebar-reverse text-brand me-2"></i>Topic Performance</h5>
              <p class="text-muted-ink small mb-0">Mastery per concept</p>
            </div>
          </div>
          <div style="height: 260px; position: relative;">
            <canvas id="topic-performance-chart"></canvas>
          </div>
        </div>
      </div>
      <div class="col-lg-5">
        <div class="card p-4 h-100">
          <div class="d-flex justify-content-between align-items-center mb-3">
            <div>
              <h5 class="mb-1 fw-bold text-ink-900"><i class="bi bi-pie-chart text-brand me-2"></i>Score Distribution</h5>
              <p class="text-muted-ink small mb-0">From recent quizzes</p>
            </div>
          </div>
          <div style="height: 260px; position: relative; display: flex; justify-content: center;">
            <canvas id="score-distribution-chart"></canvas>
          </div>
        </div>
      </div>
    </div>

    <!-- Row 3: Recent Quizzes & Achievements -->
    <div class="row g-4 mb-4">
      <div class="col-lg-7">
        <div class="card p-4 h-100">
          <div class="d-flex justify-content-between align-items-center mb-3">
            <div>
              <h5 class="mb-1 fw-bold text-ink-900"><i class="bi bi-clock-history text-brand me-2"></i>Recent Activity</h5>
              <p class="text-muted-ink small mb-0">Your latest quiz attempts</p>
            </div>
            <a href="<?php echo url('/pages/my_quizzes.php'); ?>" class="small fw-semibold text-brand text-decoration-none">
              View all <i class="bi bi-arrow-right"></i>
            </a>
          </div>
          <div class="table-responsive">
            <table class="table align-middle">
              <thead>
                <tr class="text-muted-ink small">
                  <th>Quiz</th>
                  <th>Topic</th>
                  <th>Difficulty</th>
                  <th>Date</th>
                  <th class="text-end">Action</th>
                </tr>
              </thead>
              <tbody>
                <?php if ($recent): ?>
                  <?php foreach ($recent as $q): ?>
                  <?php
                    $diff = strtolower($q['difficulty'] ?? 'medium');
                    $diffBadgeClass = 'badge-difficulty-' . ($diff === 'easy' ? 'easy' : ($diff === 'hard' ? 'hard' : 'medium'));
                  ?>
                  <tr>
                    <td>
                      <div class="fw-semibold text-ink-900"><?php echo e($q['title'] ?? 'Quiz'); ?></div>
                    </td>
                    <td><span class="text-muted-ink small"><?php echo e($q['topic'] ?? '—'); ?></span></td>
                    <td><span class="badge-soft <?php echo $diffBadgeClass; ?>"><?php echo e(ucfirst($diff)); ?></span></td>
                    <td class="text-muted-ink small"><?php echo e(date('M j, Y', strtotime((string) ($q['created_at'] ?? 'now')))); ?></td>
                    <td class="text-end">
                      <a href="<?php echo url('/pages/quiz.php?id=' . urlencode($q['id'])); ?>" class="btn btn-sm btn-outline-brand py-1 px-2 text-nowrap">Take <i class="bi bi-arrow-right ms-1"></i></a>
                    </td>
                  </tr>
                  <?php endforeach; ?>
                <?php else: ?>
                  <tr>
                    <td colspan="5" class="text-center text-muted-ink py-4">
                      <div class="py-3">
                        <i class="bi bi-journal-x fs-2 text-ink-300 d-block mb-2"></i>
                        <p class="mb-2">No quizzes generated yet.</p>
                        <a href="<?php echo url('/pages/generate.php'); ?>" class="btn btn-sm btn-brand">Generate your first quiz</a>
                      </div>
                    </td>
                  </tr>
                <?php endif; ?>
              </tbody>
            </table>
          </div>
        </div>
      </div>

      <div class="col-lg-5 d-flex flex-column gap-4">
        <div class="card p-4 flex-grow-1">
          <div class="d-flex justify-content-between align-items-center mb-3">
            <div>
              <h5 class="mb-1 fw-bold text-ink-900"><i class="bi bi-trophy text-warning me-2"></i>Achievements</h5>
              <p class="text-muted-ink small mb-0">Milestones unlocked</p>
            </div>
            <span class="badge-soft" id="achievement-count"></span>
          </div>
          <div id="achievements-grid" class="row g-2"></div>
        </div>
        
        <div class="card p-4 flex-grow-1">
          <div class="d-flex justify-content-between align-items-center mb-3">
            <div>
              <h5 class="mb-1 fw-bold text-ink-900"><i class="bi bi-award text-brand me-2"></i>Certificates</h5>
            </div>
            <a href="<?php echo url('/pages/certificates.php'); ?>" class="small fw-semibold text-brand text-decoration-none">
              View all
            </a>
          </div>
          <div id="certificates-preview">
            <p class="text-muted-ink small mb-0"><i class="bi bi-hourglass-split me-1"></i>Checking...</p>
          </div>
        </div>
      </div>
    </div>

  </main>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.1/dist/chart.umd.min.js"></script>
<script src="<?php echo url('/assets/js/app.js'); ?>"></script>
</body>
</html>
